version: '3.8'

services:
  # PostgreSQL Service
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nestjs_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs-network

  # NestJS Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: nestjs
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: nestjs_db
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
